config/routes.rb
Rails.application.routes.draw do
  get 'product/detail'
  get 'product/asc_price'
  get 'product/des_price'
  get 'product/in_stock'
  get 'product/out_stock'
  get 'product/available'
  get 'product/not_available'
  get 'product/prod_cat'
  get 'product/orders_placed'
  get 'product/line_item_details'
  get 'product/recent_order'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
end

app/models/lineitemnew.rb
class Lineitemnew < ActiveRecord::Base
end

app/models/litem.rb
class Litem < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def detail
  	@products = Product.all
  	@total_product_price = Product.pluck(:price).inject(:+)	
  	
  	product_quantities = Product.pluck(:price,:unit)
	  @total = 0
  	product_quantities.each do |product|
	   @total = @total + product[0] * product[1].to_i
	   end
	#puts total
  end


  def asc_price
  @asc_products = Product.order(:price)
  end

  def des_price
  @dsc_products = Product.order('price DESC')
  end



  def in_stock
  @products = Product.where('in_stock = ?',true)
  #@products = Product.where(in_stock: true)
  @count = Product.where('in_stock = ?',true).count
  end

  def out_stock
  @products = Product.where('in_stock = ?' ,false)
  @count = Product.where('in_stock = ?',false).count
  end

  def available
  @products = Product.where('available_from <= ?', Date.today)
  end

  def not_available
  @products = Product.where('available_from > ?', Date.today)	
  end

  def prod_cat
  	@cats = Cat.pluck(:id)
  end

  def orders_placed
    @orders = Order.all
  end

  def line_item_details
    @orders = Order.pluck(:id)
  end

  def recent_order
    @orders = Order.order('order_date DESC').limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectMgmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/asc_price.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h2> Product details by Ascending order of price </h2>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<th> Stock status </th>
		<th> Available from </th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
	<% clr = 0 %>
	<% @asc_products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/available.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing <%= @products.count %> currently available product details </h3>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<th> Stock Status </th> 
		<th> Available</th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/des_price.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h2> Product details by Desending order of price </h2>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<th> Stock status </th>
		<th> Available from </th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @dsc_products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/detail.html.erb
<h1>Product Details </h1>
<br>
<%# <%= link_to "List products by highest price",product_des_price_path %>
<h3>  Total product price = <%=@total_product_price %> </h3>
<h3>  Total stock price = <%=@total %> </h3>
<%= link_to "Order Details",product_orders_placed_path %>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> <%= link_to "^",product_asc_price_path %> Price <%= link_to "v", product_des_price_path %> </th>
		<th> Unit </th>
		<th> Stock status  <div> <%= link_to "in_stock", product_in_stock_path %> / <%= link_to "out of stock", product_out_stock_path %></th>
		<th> Availability <div> <%= link_to "available",product_available_path %> / <%= link_to "not available",product_not_available_path %> </th>
		<th> Category <div> <%= link_to "Display Categorywise products ",product_prod_cat_path %> </th> 
	</tr>
</thead>
<tbody>
	<% clr = 0 %>
	<% @products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/in_stock.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing <%= @count %> in stock products details </h3>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<!--<th> Stock Status </th> -->
		<th> Available</th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<%#<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/line_item_details.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h1> Listing lineitem details </h1>
<br>
<h2> Total income <%= Lineitemnew.pluck(:total_price).inject(:+).round(2)%> </h2>
<% @orders.each do |order| %>
<h2> Listing product details for Order number: <%= Order.find(order).order_number%> </h2>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Order Id</th>
		<th> Product Id </th>
		<th> Quantity</th>
		<th> Price </th> 
		<th> Total Price </th>
	</tr>
</thead>
<tbody>
<% clr = 0 %>
<% sum = 0 %>

		<%# #puts "category = #{cat}" %>
		<%product = Lineitemnew.where('order_id = ?', order) %>
	<% product.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.order_id %> </td>
		<td> <%= product.product_id %> </td>
		<td> <%= product.quantity %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.total_price %> </td>
		<% sum += product.total_price %>
	</tr>
	<% end %>
</tbody>
</table>
<br>
Total price for order:<%= sum %>
<%end %>

app/views/product/not_available.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing <%= @products.count %> currently not available product details  </h4>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<th> Stock Status </th> 
		<th> Available</th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/orders_placed.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing total <%= @orders.count %> order details </h3>
<br>
<%= link_to "List line item",product_line_item_details_path %>
<%= link_to "Recent order",product_recent_order_path %>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Order Date </th>
		<th> Order Number</th>
		<th> Total line Items </th>
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @orders.each do |order| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= order.order_date %> </td>
		<td> <%= order.order_number %> </td>
		<td> <%= Lineitemnew.where('order_id = ?',order.id).count %> </td>
	<% end %>
</tbody>
</table>

app/views/product/out_stock.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing <%= @count %> out of stock product details </h3>
<br>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<!--<th> Stock Status </th> -->
		<th> Available from </th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @products.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<%#<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>

app/views/product/prod_cat.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h1> Listing category wise product details </h1>
<br>
<% @cats.each do |cat| %>
<h2> Listing product details for category <%=Cat.find(cat).category_name %> </h2>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Product Name </th>
		<th> Price </th>
		<th> Unit </th>
		<th> Stock Status </th> 
		<th> Available</th>
		<th> Category </th> 
	</tr>
</thead>
<tbody>
<% clr = 0 %>

		<%# #puts "category = #{cat}" %>
		<%product = Product.where('category = ?', cat) %>
	<% product.each do |product| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= product.name %> </td>
		<td> <%= product.price %> </td>
		<td> <%= product.unit %> </td>
		<td> <%= product.in_stock %> </td>
		<td> <%= product.available_from.strftime("%a, %d, %b %Y") %> </td>
		<td> <%= Cat.find(product.category).category_name %> </td>
	</tr>
	<% end %>
</tbody>
</table>
<%end %>

app/views/product/recent_order.html.erb
<%= link_to "Home",product_detail_path %>
<br>
<h3> Listing total <%= @orders.count %> order details </h3>
<br>
<%= link_to "List line item",product_line_item_details_path %>
<table border="1">
<thead  bgcolor="yellow">
	<tr>
		<th> Order Date </th>
		<th> Order Number</th>
		<th> Total line Items </th>
	</tr>
</thead>
<tbody>
<% clr = 0 %>
	<% @orders.each do |order| %>
	<% if clr == 0 %>
		<tr bgcolor = "lightgrey"> 
		<% clr = 1%>
	<% else %>
		<% clr = 0 %>
		<tr>
	<% end %>
		<td> <%= order.order_date %> </td>
		<td> <%= order.order_number %> </td>
		<td> <%= Lineitemnew.where('order_id = ?',order.id).count %> </td>
	<% end %>
</tbody>
</table>